# Generated by Django 2.2.7 on 2020-03-01 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Harare', 'harare'), ('Chivi', 'Chivi')], max_length=200)),
                ('district', models.CharField(choices=[('Harare', 'harare'), ('Chivi', 'Chivi')], max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Organization')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
