# Generated by Django 2.2.7 on 2020-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
